### ISSUE TITLE
Ruby aws-sdk 1.66.0 MissingCredentialsError

### ISSUE THREAD

**Issue by pda** [99designs/aws-vault#40] opened 2015-10-12 20:02 UTC
Ruby's [aws-sdk 1.66.0](https://rubygems.org/gems/aws-sdk/versions/1.66.0) (the latest v1 release) fails to upload to S3 under `aws-vault`.

As shown in #33, the earlier v1.42.0 succeeds at the same operation, after an unrelated proxy parsing issue was fixed.

```
$ aws-vault --debug exec profilename -- bundle exec ./publish
DEBUG 2015/10/12 14:51:20 Parsing config file /Users/pda/.aws/config
DEBUG 2015/10/12 14:51:20 Looking up keyring for 99designs
DEBUG 2015/10/12 14:51:20 Opening keychain /Users/pda/Library/Keychains/aws-vault.keychain
DEBUG 2015/10/12 14:51:21 Opening keychain /Users/pda/Library/Keychains/aws-vault.keychain
DEBUG 2015/10/12 14:51:21 Session is expired
DEBUG 2015/10/12 14:51:21 Getting new session token for profile contests
DEBUG 2015/10/12 14:51:21 Writing session for contests to keyring
DEBUG 2015/10/12 14:51:21 Opening keychain /Users/pda/Library/Keychains/aws-vault.keychain
DEBUG 2015/10/12 14:51:21 Adding service="aws-vault", account="contests session" to osx keychain /Users/pda/Library/Keychains/aws-vault.keychain
DEBUG 2015/10/12 14:51:21 Opening keychain /Users/pda/Library/Keychains/aws-vault.keychain
DEBUG 2015/10/12 14:51:21 Removing keychain item service="aws-vault", account="contests session" from osx keychain "/Users/pda/Library/Keychains/aws-vault.keychain"
DEBUG 2015/10/12 14:51:21 Using session, expires in 3h59m59.047780732s
DEBUG 2015/10/12 14:51:21 Assuming role arn:aws:iam::068566200760:role/ReadOnly, expires in 15m0s
DEBUG 2015/10/12 14:51:22 Role token expires in 14m59.945270573s
DEBUG 2015/10/12 14:51:22 Parsing config file /Users/pda/.aws/config
DEBUG 2015/10/12 14:51:22 Metadata server listening on 127.0.0.1:54769
project/vendor/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.66.0/lib/aws/core/credential_providers.rb:140:in `credentials':  (AWS::Errors::MissingCredentialsError)
Missing Credentials.

Unable to find AWS credentials.  You can configure your AWS credentials
a few different ways:

* Call AWS.config with :access_key_id and :secret_access_key

* Export AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to ENV

* On EC2 you can run instances with an IAM instance profile and credentials
  will be auto loaded from the instance metadata service on those
  instances.

* Call AWS.config with :credential_provider.  A credential provider should
  either include AWS::Core::CredentialProviders::Provider or respond to
  the same public methods.

= Ruby on Rails

In a Ruby on Rails application you may also specify your credentials in
the following ways:

* Via a config initializer script using any of the methods mentioned above
  (e.g. RAILS_ROOT/config/initializers/aws-sdk.rb).

* Via a yaml configuration file located at RAILS_ROOT/config/aws.yml.
  This file should be formated like the default RAILS_ROOT/config/database.yml
  file.

        from project/vendor/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.66.0/lib/aws/core/credential_providers.rb:62:in `access_key_id'
        from project/vendor/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:549:in `build_request'
        from project/vendor/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:491:in `block (3 levels) in client_request'
        from project/vendor/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.66.0/lib/aws/core/response.rb:175:in `call'
        from project/vendor/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.66.0/lib/aws/core/response.rb:175:in `build_request'
        from project/vendor/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.66.0/lib/aws/core/response.rb:114:in `initialize'
        from project/vendor/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:203:in `new'
        from project/vendor/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:203:in `new_response'
        from project/vendor/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:490:in `block (2 levels) in client_request'
        from project/vendor/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:391:in `log_client_request'
        from project/vendor/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:477:in `block in client_request'
        from project/vendor/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:373:in `return_or_raise'
        from project/vendor/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:476:in `client_request'
        from (eval):3:in `put_object'
        from project/vendor/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.66.0/lib/aws/s3/s3_object.rb:1765:in `write_with_put_object'
        from project/vendor/bundle/ruby/2.2.0/gems/aws-sdk-v1-1.66.0/lib/aws/s3/s3_object.rb:611:in `write'
        from ./publish:23:in `block in <main>'
        from ./publish:16:in `each'
        from ./publish:16:in `<main>'
exit status 1
```

**Comment by lox** [comment] 2015-10-12 23:29
Ok, well I can reproduce it.

**Comment by lox** [comment] 2015-10-13 02:07
The issue comes down to this line:
https://github.com/aws/aws-sdk-ruby/blob/v1.66.0/lib/aws/core/credential_providers.rb#L425

It opts out of picking up proxies from `http_proxy`.

**Comment by lox** [comment] 2015-10-13 02:08
From the looks of it, intentionally:
https://github.com/aws/aws-sdk-ruby/commit/5af5b8dc19bed46d029e257308305c959acff56c

**Comment by lox** [comment] 2015-10-13 02:09
Looks like the latest does that too: https://github.com/aws/aws-sdk-ruby/blob/master/aws-sdk-core/lib/aws-sdk-core/instance_profile_credentials.rb#L100

**Comment by lox** [comment] 2015-10-15 05:04
This is fixed in master.

**Closed by lox** 2015-10-15 05:04 UTC
