### ISSUE TITLE
Windows Version Aws-Vault 5.1.1/5.0.1 does not work

### ISSUE THREAD

**Issue by zakswindow** [99designs/aws-vault#497] opened 2020-01-16 14:15 UTC
I tried to use aws-vault on both windows and mac. Mac is working fine. 

I installed aws-vault in Windows with choco. When i do `aws-vault add profile` then it asks for access id and secret key. it says successfully added. 
When i try aws-vault exec profile it shows:
`aws-vault: error: exec: Failed to get credentials for PROFILE: InvalidClientTokenId: The security token included in the request is invalid.
        status code: 403, request id: DDGYGDYGD-386a-11ea-b0ce-AHDAHDFGASGDF`

I investigated it. I think root cause is `aws-vault add profile` can not set `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` as Environment Variable. 

Anyone having a similar issue?

**Comment by mtibben** [comment] 2020-01-17 00:07
@zakswindow can you provide your config and the `--debug` output of your failing command

**Comment by zakswindow** [comment] 2020-01-17 10:40
config file:

**Comment by zakswindow** [comment] 2020-01-17 12:41
@mtibben fixed this issue after i installed keyring on Windows 10.

Also tried the same thing in Ubuntu sub-shell, it works. 

**issue1:**
however, i use jenkins x with kubernetes. if i use jx get applications, it doesn't work when i use aws-vault but it works when i don't use aws-vault with access key and secret key as env var. its happening on mac, ubuntu, and windows. this is the main issue we're having. will appreciate if you have any solution for this.
when i run `kubectl get nodes` i can see the nodes,` jx get applications` command don not return anything rather than `No applications found`.

we have windows, ubuntu and mac user. its important that we get it working.

issue2:
On Ubuntu, i am trying to use --server flag.
my command is: `aws-vault --debug exec profile --server` but i get error. 
`
2020/01/17 12:39:19 [keyring] Expanded file dir to /home/zak/.awsvault/keys/
2020/01/17 12:39:19 [keyring] Expanded file dir to /home/zak/.awsvault/keys/
2020/01/17 12:39:19 Generated credentials ****************7COL using AssumeRole, expires in 59m59.7228923s
2020/01/17 12:39:19 Starting `aws-vault server` as root in the background
2020/01/17 12:39:19 Starting local instance role server on 127.0.0.1:9099
2020/01/17 12:39:19 Setting subprocess env: AWS_DEFAULT_REGION=eu-west-2, AWS_REGION=eu-west-2
aws-vault: error: Server failed: exit status 2
`

**Comment by zakswindow** [comment] 2020-01-17 12:51
**issue 3:**

command `aws-vault --debug exec abc --duration 8h` on mac and Ubuntu doesn't work, did not test Windows yet. aws-vault version is 5.1.1.

**output:**
,2020/01/17 12:44:27 [keyring] Considering backends: [keychain pass file]
2020/01/17 12:44:27 Loading config file /Users/zakhussain/.aws/config
2020/01/17 12:44:27 Parsing config file /Users/zakhussain/.aws/config
2020/01/17 12:44:27 [keyring] Querying keychain for service="aws-vault", keychain="aws-vault.keychain"
2020/01/17 12:44:27 [keyring] Found 1 results
2020/01/17 12:44:27 [keyring] Querying keychain for service="aws-vault", keychain="aws-vault.keychain"
2020/01/17 12:44:27 [keyring] Found 1 results
2020/01/17 12:44:27 profile xyz: using stored credentials
2020/01/17 12:44:27 profile xyz: using GetSessionToken (using MFA)
2020/01/17 12:44:27 profile abc: using AssumeRole (chained MFA)
2020/01/17 12:44:27 Looking for sessions for xyz
2020/01/17 12:44:27 Looking up all keys in keyring
2020/01/17 12:44:27 [keyring] Querying keychain for service="aws-vault", keychain="aws-vault.keychain"
2020/01/17 12:44:27 [keyring] Found 1 results
Enter token for arn:aws:iam::000000000:mfa/zak@example.com: 585551
2020/01/17 12:44:33 Looking up keyring for 'xyz'
2020/01/17 12:44:33 [keyring] Querying keychain for service="aws-vault", account="xyz", keychain="aws-vault.keychain"
2020/01/17 12:44:33 [keyring] Found item "aws-vault (xyz)"
2020/01/17 12:44:33 Generated credentials ****************F5UE using GetSessionToken, expires in 7h59m59.014271s
2020/01/17 12:44:33 Writing session for xyz to keyring: "session,eXRyZWUtaWFt,YXJurfUYGYGgggUGUGUGggggSSSSSSRDRDtZmEvemFrQHktdHJlZS5jb20,1579293873"
2020/01/17 12:44:33 [keyring] Checking keychain status
2020/01/17 12:44:33 [keyring] Keychain status returned nil, keychain exists
2020/01/17 12:44:33 [keyring] Keychain item trusts keyring
2020/01/17 12:44:33 [keyring] Adding service="aws-vault", label="aws-vault session for xyz", account="session,eXRyZWUtaWFt,hgrsJHSkhhTFpoipHIHIUNzMxMjY2NjptZmEvemFrQHktdHJlZS5jb20,1579293873", trusted=true to osx keychain "aws-vault.keychain"
aws-vault: error: exec: Failed to get credentials for abc: ValidationError: The requested DurationSeconds exceeds the 1 hour session limit for roles assumed by role chaining.
	status code: 400, request id: 1cf2c042-3927-11ea-ae95-77c948eb8512`

I can confirm that the role i am trying to use has 8h maximum session limit setup.

**Comment by zakswindow** [comment] 2020-01-17 12:53
@mtibben Thanks for your time. Hope it helps. I tried to explain as much as possible. Let me know if you need more details.

**Comment by zakswindow** [comment] 2020-01-17 12:55
CONFIG file for aws as follows:
`
[profile xyz]
mfa_serial=arn:aws:iam::54543534534:mfa/zak@domain.com
region = eu-west-2

[profile abc]
region=eu-west-2
role_arn=arn:aws:iam::11111111111:role/ExampleAccessRole
source_profile=xyz
mfa_serial=arn:aws:iam::54543534534:mfa/zak@domain.com
`

**Comment by zakswindow** [comment] 2020-01-17 14:32
> **ISSUE-3:**
> 
> command `aws-vault --debug exec abc --duration 8h` on mac and Ubuntu doesn't work, did not test Windows yet. aws-vault version is 5.1.1.
> 
> **OUTPUT:**
> `,2020/01/17 12:44:27 [keyring] Considering backends: [keychain pass file] 2020/01/17 12:44:27 Loading config file /Users/zakhussain/.aws/config 2020/01/17 12:44:27 Parsing config file /Users/zakhussain/.aws/config 2020/01/17 12:44:27 [keyring] Querying keychain for service="aws-vault", keychain="aws-vault.keychain" 2020/01/17 12:44:27 [keyring] Found 1 results 2020/01/17 12:44:27 [keyring] Querying keychain for service="aws-vault", keychain="aws-vault.keychain" 2020/01/17 12:44:27 [keyring] Found 1 results 2020/01/17 12:44:27 profile xyz: using stored credentials 2020/01/17 12:44:27 profile xyz: using GetSessionToken (using MFA) 2020/01/17 12:44:27 profile abc: using AssumeRole (chained MFA) 2020/01/17 12:44:27 Looking for sessions for xyz 2020/01/17 12:44:27 Looking up all keys in keyring 2020/01/17 12:44:27 [keyring] Querying keychain for service="aws-vault", keychain="aws-vault.keychain" 2020/01/17 12:44:27 [keyring] Found 1 results Enter token for arn:aws:iam::000000000:mfa/zak@example.com: 585551 2020/01/17 12:44:33 Looking up keyring for 'xyz' 2020/01/17 12:44:33 [keyring] Querying keychain for service="aws-vault", account="xyz", keychain="aws-vault.keychain" 2020/01/17 12:44:33 [keyring] Found item "aws-vault (xyz)" 2020/01/17 12:44:33 Generated credentials ****************F5UE using GetSessionToken, expires in 7h59m59.014271s 2020/01/17 12:44:33 Writing session for xyz to keyring: "session,eXRyZWUtaWFt,YXJurfUYGYGgggUGUGUGggggSSSSSSRDRDtZmEvemFrQHktdHJlZS5jb20,1579293873" 2020/01/17 12:44:33 [keyring] Checking keychain status 2020/01/17 12:44:33 [keyring] Keychain status returned nil, keychain exists 2020/01/17 12:44:33 [keyring] Keychain item trusts keyring 2020/01/17 12:44:33 [keyring] Adding service="aws-vault", label="aws-vault session for xyz", account="session,eXRyZWUtaWFt,hgrsJHSkhhTFpoipHIHIUNzMxMjY2NjptZmEvemFrQHktdHJlZS5jb20,1579293873", trusted=true to osx keychain "aws-vault.keychain" aws-vault: error: exec: Failed to get credentials for abc: ValidationError: The requested DurationSeconds exceeds the 1 hour session limit for roles assumed by role chaining. status code: 400, request id: 1cf2c042-3927-11ea-ae95-77c948eb8512`
> 
> I can confirm that the role i am trying to use has 8h maximum session limit setup.

I have downloaded 5.1.2, and --duration is now working for assume role.

**Comment by zakswindow** [comment] 2020-01-17 14:51
**UPDATE ON ISSUE-2**

After installing 5.1.2, --server flag is working on MAC, the command is:
`aws-vault --debug exec sample-profile --duration 8h --no-session --server`

however, not working with Ubuntu; it says : `server failed exit status 2`

**Comment by mtibben** [comment] 2020-02-14 03:08
@zakswindow I can't reproduce. And your command above includes "profile" that does not exist in your provided config.

Can you please
1. get the latest version of aws-vault (v5.3.0)
2. confirm your `.aws/config`
3. provide the full output of a single `aws-vault --debug exec <profile>` that is failing for you (the executed command is irrelevant, we're only interested in what aws-vault is doing)

**Comment by mtibben** [comment] 2020-02-20 10:54
Closing pending more complete information

**Closed by mtibben** 2020-02-20 10:54 UTC
