### ISSUE TITLE
Suggestion: Automatically open SSO page when tokens are expired instead of showing an error on the first run

### ISSUE THREAD

**Issue by christophetd** [99designs/aws-vault#639] opened 2020-08-24 07:57 UTC
Version: v6.0.0-beta10

Here's the behavior with AWS SSO when a token is expired:

```
$ aws-vault exec myvault
aws-vault: error: exec: Failed to get credentials for myvault: Token expired
$ aws-vault exec myvault
Opening the SSO authorization page in your default browser (use Ctrl-C to abort)                                                                                                        
https://device.sso.eu-central-1.amazonaws.com/?user_code=xxx
```

From a usability perspective and to avoid confusing users, it seems that it would make a lot of sense to directly open the SSO authorization page as soon as a SSO token is identified as expired?

**Comment by mjburling** [comment] 2020-08-25 15:15
Hi @christophetd!

I've been using using v6.0.0-beta5, but I haven't experienced this yet. I've just downloaded beta10 and I'll let you know how it goes! In the meantime, I wonder if it might be down to a difference in the `~/.aws/config`? One such AWS SSO-enabled profile looks like this:

```
[default]
cli_pager=

[profile admin]
region=us-east-1
sso_start_url = https://my-company.awsapps.com/start
sso_region = us-east-1
sso_account_id = 123467890
sso_role_name = AWSAdministratorAccess
output = table
```

Can I assume that yours looks similar?

**Comment by FernandoMiguel** [comment] 2020-08-25 15:26
i got this today on beta10

**Comment by christophetd** [comment] 2020-08-25 16:47
@mjburling Yes, mine looks similar! 

```
[default]
sso_start_url=https://company.awsapps.com/start
sso_region=eu-central-1
cli_pager=
region=eu-west-1

[okta]
aws_saml_url=home/amazon_aws/xxx

[profile myvault]
sso_account_id=123456
sso_role_name=AdminAccess
```

**Comment by mjburling** [comment] 2020-08-25 17:45
I regret to inform you that I let my session expire in `aws-vault`, and... running again actually worked _better_ than it did in beta5? Perhaps this is by design, I guess I haven't kept up with the development. My session at awsapps.com/start is longer than the session to any specific account, and upon running `aws-vault exec admin`, it just renewed the session without even forwarding me to the browser. 

Wondering if this isn't some how related to the problem described in https://github.com/99designs/aws-vault/issues/642?

**Comment by mjburling** [comment] 2020-08-26 12:39
> I regret to inform you that I let my session expire in `aws-vault`, and... running again actually worked _better_ than it did in beta5? Perhaps this is by design, I guess I haven't kept up with the development. My session at awsapps.com/start is longer than the session to any specific account, and upon running `aws-vault exec admin`, it just renewed the session without even forwarding me to the browser.

I was wrong. I'm not sure how I achieved the above, but I'm getting the same behavior as described by @christophetd and attested by @FernandoMiguel. I've reverted to beta5 for now.

**Comment by mtibben** [comment] 2020-08-29 08:51
Has the behaviour changed in [v6.0.0-beta11](https://github.com/99designs/aws-vault/releases/tag/v6.0.0-beta11)?

**Comment by mtibben** [comment] 2020-08-29 10:23
I believe this should be fixed [v6.0.0-beta12](https://github.com/99designs/aws-vault/releases/tag/v6.0.0-beta12), can you confirm?

**Comment by FernandoMiguel** [comment] 2020-08-29 10:33
I missed the two releases. Will try next week

**Comment by christophetd** [comment] 2020-08-31 07:02
Looks great for me on v6.0.0-beta13! @FernandoMiguel do you confirm?

**Closed** 2020-09-03 08:00 UTC
