### ISSUE TITLE
ability refresh sts tokens in a sub shell from aws-vault exec

### ISSUE THREAD

**Issue by jedi4ever** [99designs/aws-vault#72] opened 2016-07-24 21:08 UTC
sometimes we want to work in a certain environment f.i. staging
we run the 'aws-vault exec staging -- bash'
we use the AWS-VAULT var to show it into our prompt
it would be nice to have a way to update the credentials while in this subshell

**Comment by lox** [comment] 2016-07-25 09:21
I do that too https://github.com/lox/dotfiles/blob/master/aws/aws.zsh#L6

Currently the only way to update credentials is to either create another sub-shell or use the `--server` option. Any reason you don't use either of those approaches? Also not sure how this correlates to the `AWS_VAULT` env var? 

Perhaps I'm not understanding.

**Comment by jedi4ever** [comment] 2016-07-25 09:32
no relation with `AWS_VAULT` just that it nicely indicated your in a subshell.

I guess I could source in a new pair of tokens in the existing subshell if there was a way to `export` a new set of tokens.

`$(aws-vault export profile1)` where it would output `export AWS...= bla`

I can't use the server as it will make all my existing shells use a partical env token.
I like to have each shell window have it's own set of vars/tokens.

**Comment by lox** [comment] 2016-07-25 09:35
Ah right. Couldn't you just create a sub-sub shell with new credentials? If you unset AWS_VAULT you can simply re-run the command and get a new subshell.

**Comment by lox** [comment] 2016-07-25 09:37
Some background on some of the design decisions are in https://github.com/99designs/aws-vault/issues/41

**Comment by lox** [comment] 2016-07-25 09:40
I'm reluctant to re-introduce an export mechanism, I think it makes it too easy to do things that are dangerous from a security perspective. To me the fact that `aws-vault` handles the subshells and makes it quite hard to do silly things is something that differentiates it from alternatives.

**Comment by lox** [comment] 2016-07-25 09:44
If you wanted to, you could have a function that extracted the AWS vars from a subshell:

```bash
aws_vault_export() {
   aws-vault exec $1 -- env | grep AWS | sed -e 's/^/export\ /'
}
```

Then `eval "$(aws_vault_export profile1)`

**Comment by lox** [comment] 2016-07-25 09:45
I'd certainly accept a PR that set the profile name in an env set into the subshell (`AWS_VAULT_PROFILE`), that would make the above a lot easier.

**Comment by lox** [comment] 2016-07-25 09:47
Better yet, don't use bash as your subshell, run every command with it's own subshell.

**Comment by lox** [comment] 2016-07-25 09:50
A magical shell way to do this would be to automatically prefix commands with `aws-vault exec $AWS_VAULT_PROFILE` if you have `AWS_VAULT_PROFILE` and `AWS_VAULT_AUTOEXEC`. 

In zsh this would be done with `precmd`, bash has a hackier way of doing it http://superuser.com/questions/175799/does-bash-have-a-hook-that-is-run-before-executing-a-command

**Comment by dball** [comment] 2016-08-16 02:56
As it turns out, this seems to be a problem when using aws-vault with leiningen, a popular project management tool for clojure apps. Leiningen itself (usually) runs in one process, and runs subprocesses to perform tasks.

There are various workarounds, but this is a bit limiting. The ability to have aws-vault export the env vars would be nice.

**Comment by lox** [comment] 2016-08-16 10:44
Could you provide an example @dball? I'm still not understanding what the issue is.

**Comment by dball** [comment] 2016-08-16 13:47
Hmm, sorry, I seem to have been mistaken. When I reproduce with a simpler test case, I do see the environmental variables in my child process.

**Comment by lox** [comment] 2016-08-16 15:27
@jedi4ever I am going to close this. If you can provide some more detail, happy to re-open.

**Closed by lox** 2016-08-16 15:27 UTC

**Comment by jedi4ever** [comment] 2016-08-17 16:27
no worries @lox
