### ISSUE TITLE
Docker + file backend

### ISSUE THREAD

**Issue by gcoxmoz** [99designs/aws-vault#93] opened 2016-09-23 22:32 UTC
This is probably a wacko edgecase, but I'm not sure where to go with this.  Docker image, ubuntu14.04, and aws-vault v3.5.0 package added to it:

    # aws-vault --backend=file add foo
    Enter Access Key ID: 123
    Enter Secret Access Key: 456
    user: Current not implemented on linux/amd64

**Comment by lox** [comment] 2016-09-26 22:10
Not a wacko edgecase, will investigate the cause of this.

**Comment by lox** [comment] 2016-09-27 03:43
This is due to https://github.com/golang/go/issues/6376, which basically means that `user.Current()` needs cgo. 

You could compile the binary on linux and it would work until we get a fix in place.

**Comment by bradfeehan** [comment] 2016-09-27 04:20
Does that mean you compile on macOS, cross compiling to build the Linux target? It seems like the linked issue is trying to deal with the inverse, where Linux is unlikely to have a "macOS cross toolchain". But if you're already building on macOS, maybe you could create the Linux target from inside a Docker container to be building natively on Linux?

**Comment by lox** [comment] 2016-09-27 04:21
Indeed, we do at the minute as most of the truly magical Keychain stuff needs a darwin clang setup. 

We could cross-compile the linux one in a docker container, but how about Windows? :)

**Comment by lox** [comment] 2016-09-27 04:25
See https://github.com/99designs/aws-vault/pull/94

**Comment by bradfeehan** [comment] 2016-09-27 04:25
Fair! Bless me for forgetting about Windows, not sure how that happened.. 😄

**Comment by lox** [comment] 2016-09-27 04:26
Yup, me too.

**Comment by lox** [comment] 2016-10-01 09:35
Closing, this is fixed in master and will put out a release soon. Thanks for raising the issue @gcoxmoz.

**Closed by lox** 2016-10-01 09:35 UTC
