### ISSUE TITLE
aws-vault: error: Server failed: exit status 1

### ISSUE THREAD

**Issue by FernandoMiguel** [99designs/aws-vault#207] opened 2017-12-20 11:52 UTC
$ aws-vault server --debug
2017/12/20 11:49:21 Loading config file /Users/fernando/.aws/config
2017/12/20 11:49:21 Parsing config file /Users/fernando/.aws/config
aws-vault: error: Server failed: exit status 1

$ aws-vault --version
v4.1.0

MacOS 10.13.3 Beta (17D20a)

**Comment by astanciu** [comment] 2017-12-20 22:51
maybe run with sudo since it binds on port 80?

**Comment by lox** [comment] 2017-12-21 04:01
`aws-vault server` isn't meant to be run directly, it should be an invisible command. What are you trying to do @FernandoMiguel?

**Comment by FernandoMiguel** [comment] 2017-12-21 07:38
@astanciu if it requires sudo, my expectations is that it should ask for it when needed 

@lox was trying to run in server mode, and that option showed in the help menu, so I tried.

After poking a bit I found the -s in the exec command too, and that seems to work for most cases. Couldn't get it to work with terraform and assume roles, but without server mode it works fine.

But back to your question, if it is supposed to be an invisible command why is it listed as one of the options of --help?

**Comment by astanciu** [comment] 2017-12-22 14:16
How is it supposed to be run then? The docs are not clear on this.

**Comment by FernandoMiguel** [comment] 2017-12-22 16:10
Exactly.
The way I found is
aws-vault exec profile --server

-- 
Fernando Miguel

**Comment by astanciu** [comment] 2017-12-22 17:06
@FernandoMiguel and even that is a bit unconventional. It appears to start a new shell session and the server is running in the background. Would be nice if this was cleaned up a bit. An option to run server as daemon/background, otherwise show server logs would be good.

**Comment by lox** [comment] 2017-12-22 21:46
Yup, I hear you, it's not well documented or clear. The design has been carefully thought over though, and is the way it is for good reason. I've started a PR that will improve the docs and make this clearer, check out https://github.com/99designs/aws-vault/pull/208.

**Comment by lox** [comment] 2018-01-02 00:00
I'm going to close this one. We will work on docs in #208, but as it stands this is the expected behaviour of manually calling the server command.

**Closed by lox** 2018-01-02 00:00 UTC
